services:
  # MongoDB Database
  mongo:
    image: mongo:8.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # Backend Service (Express + Node)
  backend:
    build:
      context: ./backend
    container_name: expense-backend
    restart: always
    ports:
      - "5001:5000" # host:container
    environment:
      MONGO_URI: mongodb://mongo:27017/expenseTracker
      NODE_ENV: development
      JWT_SECRET: mystrongsecret123
      PORT: 5000
    depends_on:
      - mongo
    volumes:
      - ./backend:/app
      - /app/node_modules

  # Frontend Service (React)
  frontend:
    build:
      context: ./frontend
    container_name: expense-frontend
    restart: always
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://localhost:5001
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mongo-data:
